/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api


  /**
   * An enumeration of the types an activity may have. Note that this enumeration does not include new sport types (e.g. MountainBikeRide, EMountainBikeRide), activities with these sport types will have the corresponding activity type (e.g. Ride for MountainBikeRide, EBikeRide for EMountainBikeRide)
   */

object ActivityType extends Enumeration {
    type ActivityType = ActivityType.Value
    val AlpineSki = Value("AlpineSki")
    val BackcountrySki = Value("BackcountrySki")
    val Canoeing = Value("Canoeing")
    val Crossfit = Value("Crossfit")
    val EBikeRide = Value("EBikeRide")
    val Elliptical = Value("Elliptical")
    val Golf = Value("Golf")
    val Handcycle = Value("Handcycle")
    val Hike = Value("Hike")
    val IceSkate = Value("IceSkate")
    val InlineSkate = Value("InlineSkate")
    val Kayaking = Value("Kayaking")
    val Kitesurf = Value("Kitesurf")
    val NordicSki = Value("NordicSki")
    val Ride = Value("Ride")
    val RockClimbing = Value("RockClimbing")
    val RollerSki = Value("RollerSki")
    val Rowing = Value("Rowing")
    val Run = Value("Run")
    val Sail = Value("Sail")
    val Skateboard = Value("Skateboard")
    val Snowboard = Value("Snowboard")
    val Snowshoe = Value("Snowshoe")
    val Soccer = Value("Soccer")
    val StairStepper = Value("StairStepper")
    val StandUpPaddling = Value("StandUpPaddling")
    val Surfing = Value("Surfing")
    val Swim = Value("Swim")
    val Velomobile = Value("Velomobile")
    val VirtualRide = Value("VirtualRide")
    val VirtualRun = Value("VirtualRun")
    val Walk = Value("Walk")
    val WeightTraining = Value("WeightTraining")
    val Wheelchair = Value("Wheelchair")
    val Windsurf = Value("Windsurf")
    val Workout = Value("Workout")
    val Yoga = Value("Yoga")
}
