/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

case class ClubActivity(
  athlete: Option[MetaAthlete] = None,
  /* The name of the activity */
  name: Option[String] = None,
  /* The activity's distance, in meters */
  distance: Option[Float] = None,
  /* The activity's moving time, in seconds */
  moving_time: Option[Int] = None,
  /* The activity's elapsed time, in seconds */
  elapsed_time: Option[Int] = None,
  /* The activity's total elevation gain. */
  total_elevation_gain: Option[Float] = None,
  `type`: Option[ActivityType] = None,
  sport_type: Option[SportType] = None,
  /* The activity's workout type */
  workout_type: Option[Int] = None
)

object ClubActivityEnums {

}
