/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

import java.time.OffsetDateTime

case class DetailedActivity(
  /* The unique identifier of the activity */
  id: Option[Long] = None,
  /* Resource state, indicates level of detail */
  resource_state: Option[Int] = None,
  /* The identifier provided at upload time */
  external_id: Option[String] = None,
  /* The identifier of the upload that resulted in this activity */
  upload_id: Option[Long] = None,
  athlete: Option[MetaAthlete] = None,
  /* The name of the activity */
  name: Option[String] = None,
  /* The activity's distance, in meters */
  distance: Option[Float] = None,
  /* The activity's moving time, in seconds */
  moving_time: Option[Int] = None,
  /* The activity's elapsed time, in seconds */
  elapsed_time: Option[Int] = None,
  /* The activity's total elevation gain. */
  total_elevation_gain: Option[Float] = None,
  /* The activity's highest elevation, in meters */
  elev_high: Option[Float] = None,
  /* The activity's lowest elevation, in meters */
  elev_low: Option[Float] = None,
  `type`: Option[ActivityType] = None,
  sport_type: Option[SportType] = None,
  /* The time at which the activity was started. */
  start_date: Option[OffsetDateTime] = None,
  /* The time at which the activity was started in the local timezone. */
  start_date_local: Option[OffsetDateTime] = None,
  /* The timezone of the activity */
  timezone: Option[String] = None,
  /* The offset from UTC time in seconds */
  utc_offset: Option[Int] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  start_latlng: Option[Seq[Float]] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  end_latlng: Option[Seq[Float]] = None,
  /* The number of achievements gained during this activity */
  achievement_count: Option[Int] = None,
  /* The number of kudos given for this activity */
  kudos_count: Option[Int] = None,
  /* The number of comments for this activity */
  comment_count: Option[Int] = None,
  /* The number of athletes for taking part in a group activity */
  athlete_count: Option[Int] = None,
  /* The number of Instagram photos for this activity */
  photo_count: Option[Int] = None,
  /* The number of Instagram and Strava photos for this activity */
  total_photo_count: Option[Int] = None,
  map: Option[PolylineMap] = None,
  /* Whether this activity was recorded on a training machine */
  trainer: Option[Boolean] = None,
  /* Whether this activity is a commute */
  commute: Option[Boolean] = None,
  /* Whether this activity was created manually */
  manual: Option[Boolean] = None,
  /* Whether this activity is private */
  `private`: Option[Boolean] = None,
  /* Whether this activity is flagged */
  flagged: Option[Boolean] = None,
  /* The activity's workout type */
  workout_type: Option[Int] = None,
  /* The unique identifier of the upload in string format */
  upload_id_str: Option[String] = None,
  /* The activity's average speed, in meters per second */
  average_speed: Option[Float] = None,
  /* The activity's max speed, in meters per second */
  max_speed: Option[Float] = None,
  /* Whether the logged-in athlete has kudoed this activity */
  has_kudoed: Option[Boolean] = None,
  /* Whether the activity is muted */
  hide_from_home: Option[Boolean] = None,
  /* The id of the gear for the activity */
  gear_id: Option[String] = None,
  /* Whether this activity was created from an accepted tag */
  from_accepted_tag: Option[Boolean] = None,
  /* The total work done in kilojoules during this activity. Rides only */
  kilojoules: Option[Float] = None,
  /* Average power output in watts during this activity. Rides only */
  average_watts: Option[Float] = None,
  /* Whether the watts are from a power meter, false if estimated */
  device_watts: Option[Boolean] = None,
  /* Rides with power meter data only */
  max_watts: Option[Int] = None,
  /* Similar to Normalized Power. Rides with power meter data only */
  weighted_average_watts: Option[Int] = None,
  /* The description of the activity */
  description: Option[String] = None,
  photos: Option[PhotosSummary] = None,
  gear: Option[SummaryGear] = None,
  /* The number of kilocalories consumed during this activity */
  calories: Option[Float] = None,
  /* Whether the activity has heartrate data */
  has_heartrate: Option[Boolean] = None,
  /* The heart rate of the athlete during this activity. In BPM */
  average_heartrate: Option[Float] = None,
  /* The maximum heart rate of the athlete during this activity. In BPM */
  max_heartrate: Option[Float] = None,
  /* The average cadence during this activity */
  average_cadence: Option[Float] = None,
  /* The average temperature during this activity */
  average_temp: Option[Int] = None,
  /* The number of PRs gained during this activity */
  pr_count: Option[Int] = None,
  /* The suffer score of the activity */
  suffer_score: Option[Int] = None,
  segment_efforts: Option[Seq[DetailedSegmentEffort]] = None,
  /* The name of the device used to record the activity */
  device_name: Option[String] = None,
  /* The token used to embed a Strava activity */
  embed_token: Option[String] = None,
  /* The splits of this activity in metric units (for runs) */
  splits_metric: Option[Seq[Split]] = None,
  /* The splits of this activity in imperial units (for runs) */
  splits_standard: Option[Seq[Split]] = None,
  laps: Option[Seq[Lap]] = None,
  best_efforts: Option[Seq[DetailedSegmentEffort]] = None,
  /* The partner brand tag */
  partner_brand_tag: Option[String] = None,
  /* Whether the athlete has opted out of segment leaderboards */
  segment_leaderboard_opt_out: Option[Boolean] = None,
  /* Whether the athlete has opted out of leaderboards */
  leaderboard_opt_out: Option[Boolean] = None
)

object DetailedActivityEnums {

}
