/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

import java.time.OffsetDateTime

case class DetailedSegment(
  /* The unique identifier of this segment */
  id: Option[Long] = None,
  /* The name of this segment */
  name: Option[String] = None,
  activity_type: Option[DetailedSegmentEnums.ActivityType] = None,
  /* The segment's distance, in meters */
  distance: Option[Float] = None,
  /* The segment's average grade, in percents */
  average_grade: Option[Float] = None,
  /* The segments's maximum grade, in percents */
  maximum_grade: Option[Float] = None,
  /* The segments's highest elevation, in meters */
  elevation_high: Option[Float] = None,
  /* The segments's lowest elevation, in meters */
  elevation_low: Option[Float] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  start_latlng: Option[Seq[Float]] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  end_latlng: Option[Seq[Float]] = None,
  /* The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. */
  climb_category: Option[Int] = None,
  /* The segments's city. */
  city: Option[String] = None,
  /* The segments's state or geographical region. */
  state: Option[String] = None,
  /* The segment's country. */
  country: Option[String] = None,
  /* Whether this segment is private. */
  `private`: Option[Boolean] = None,
  athlete_pr_effort: Option[SummaryPRSegmentEffort] = None,
  athlete_segment_stats: Option[SummarySegmentEffort] = None,
  /* The time at which the segment was created. */
  created_at: Option[OffsetDateTime] = None,
  /* The time at which the segment was last updated. */
  updated_at: Option[OffsetDateTime] = None,
  /* The segment's total elevation gain. */
  total_elevation_gain: Option[Float] = None,
  map: Option[PolylineMap] = None,
  /* The total number of efforts for this segment */
  effort_count: Option[Int] = None,
  /* The number of unique athletes who have an effort for this segment */
  athlete_count: Option[Int] = None,
  /* Whether this segment is considered hazardous */
  hazardous: Option[Boolean] = None,
  /* The number of stars for this segment */
  star_count: Option[Int] = None
)

object DetailedSegmentEnums {

  type ActivityType = ActivityType.Value
  object ActivityType extends Enumeration {
    val Ride = Value("Ride")
    val Run = Value("Run")
  }

}
