/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api


case class ExplorerSegment(
  /* The unique identifier of this segment */
  id: Option[Long] = None,
  /* The name of this segment */
  name: Option[String] = None,
  /* The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. If climb_category = 5, climb_category_desc = HC. If climb_category = 2, climb_category_desc = 3. */
  climb_category: Option[Int] = None,
  /* The description for the category of the climb */
  climb_category_desc: Option[ExplorerSegmentEnums.ClimbCategoryDesc] = None,
  /* The segment's average grade, in percents */
  avg_grade: Option[Float] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  start_latlng: Option[Seq[Float]] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  end_latlng: Option[Seq[Float]] = None,
  /* The segments's evelation difference, in meters */
  elev_difference: Option[Float] = None,
  /* The segment's distance, in meters */
  distance: Option[Float] = None,
  /* The polyline of the segment */
  points: Option[String] = None
)

object ExplorerSegmentEnums {

  type ClimbCategoryDesc = ClimbCategoryDesc.Value
  object ClimbCategoryDesc extends Enumeration {
    val NC = Value("NC")
    val `4` = Value("4")
    val `3` = Value("3")
    val `2` = Value("2")
    val `1` = Value("1")
    val HC = Value("HC")
  }

}
