/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

import java.time.OffsetDateTime

case class Lap(
  /* The unique identifier of this lap */
  id: Option[Long] = None,
  activity: Option[MetaActivity] = None,
  athlete: Option[MetaAthlete] = None,
  /* The lap's average cadence */
  average_cadence: Option[Float] = None,
  /* The lap's average speed */
  average_speed: Option[Float] = None,
  /* The lap's distance, in meters */
  distance: Option[Float] = None,
  /* The lap's elapsed time, in seconds */
  elapsed_time: Option[Int] = None,
  /* The start index of this effort in its activity's stream */
  start_index: Option[Int] = None,
  /* The end index of this effort in its activity's stream */
  end_index: Option[Int] = None,
  /* The index of this lap in the activity it belongs to */
  lap_index: Option[Int] = None,
  /* The maximum speed of this lat, in meters per second */
  max_speed: Option[Float] = None,
  /* The lap's moving time, in seconds */
  moving_time: Option[Int] = None,
  /* The name of the lap */
  name: Option[String] = None,
  /* The athlete's pace zone during this lap */
  pace_zone: Option[Int] = None,
  split: Option[Int] = None,
  /* The time at which the lap was started. */
  start_date: Option[OffsetDateTime] = None,
  /* The time at which the lap was started in the local timezone. */
  start_date_local: Option[OffsetDateTime] = None,
  /* The elevation gain of this lap, in meters */
  total_elevation_gain: Option[Float] = None
)

