/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api


case class LatLngStream(
  /* The number of data points in this stream */
  original_size: Option[Int] = None,
  /* The level of detail (sampling) in which this stream was returned */
  resolution: Option[LatLngStreamEnums.Resolution] = None,
  /* The base series used in the case the stream was downsampled */
  series_type: Option[LatLngStreamEnums.SeriesType] = None,
  /* The sequence of lat/long values for this stream */
  data: Option[Seq[Seq[Float]]] = None
)

object LatLngStreamEnums {

  type Resolution = Resolution.Value
  type SeriesType = SeriesType.Value
  object Resolution extends Enumeration {
    val Low = Value("low")
    val Medium = Value("medium")
    val High = Value("high")
  }

  object SeriesType extends Enumeration {
    val Distance = Value("distance")
    val Time = Value("time")
  }

}
