/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

import java.time.OffsetDateTime

case class Route(
  athlete: Option[SummaryAthlete] = None,
  /* The description of the route */
  description: Option[String] = None,
  /* The route's distance, in meters */
  distance: Option[Float] = None,
  /* The route's elevation gain. */
  elevation_gain: Option[Float] = None,
  /* The unique identifier of this route */
  id: Option[Long] = None,
  /* The unique identifier of the route in string format */
  id_str: Option[String] = None,
  map: Option[PolylineMap] = None,
  /* The name of this route */
  name: Option[String] = None,
  /* Whether this route is private */
  `private`: Option[Boolean] = None,
  /* Whether this route is starred by the logged-in athlete */
  starred: Option[Boolean] = None,
  /* An epoch timestamp of when the route was created */
  timestamp: Option[Int] = None,
  /* This route's type (1 for ride, 2 for runs) */
  `type`: Option[Int] = None,
  /* This route's sub-type (1 for road, 2 for mountain bike, 3 for cross, 4 for trail, 5 for mixed) */
  sub_type: Option[Int] = None,
  /* The time at which the route was created */
  created_at: Option[OffsetDateTime] = None,
  /* The time at which the route was last updated */
  updated_at: Option[OffsetDateTime] = None,
  /* Estimated time in seconds for the authenticated athlete to complete route */
  estimated_moving_time: Option[Int] = None,
  /* The segments traversed by this route */
  segments: Option[Seq[SummarySegment]] = None,
  /* The custom waypoints along this route */
  waypoints: Option[Seq[Waypoint]] = None
)

