/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api


case class StreamSet(
  time: Option[TimeStream] = None,
  distance: Option[DistanceStream] = None,
  latlng: Option[LatLngStream] = None,
  altitude: Option[AltitudeStream] = None,
  velocity_smooth: Option[SmoothVelocityStream] = None,
  heartrate: Option[HeartrateStream] = None,
  cadence: Option[CadenceStream] = None,
  watts: Option[PowerStream] = None,
  temp: Option[TemperatureStream] = None,
  moving: Option[MovingStream] = None,
  grade_smooth: Option[SmoothGradeStream] = None
)

