/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

case class SummaryClub(
  /* The club's unique identifier. */
  id: Option[Long] = None,
  /* Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\" */
  resource_state: Option[Int] = None,
  /* The club's name. */
  name: Option[String] = None,
  /* URL to a 60x60 pixel profile picture. */
  profile_medium: Option[String] = None,
  /* URL to a ~1185x580 pixel cover photo. */
  cover_photo: Option[String] = None,
  /* URL to a ~360x176  pixel cover photo. */
  cover_photo_small: Option[String] = None,
  /* Deprecated. Prefer to use activity_types. */
  sport_type: Option[SummaryClubEnums.SportType] = None,
  /* The activity types that count for a club. This takes precedence over sport_type. */
  activity_types: Option[Seq[ActivityType]] = None,
  /* The club's city. */
  city: Option[String] = None,
  /* The club's state or geographical region. */
  state: Option[String] = None,
  /* The club's country. */
  country: Option[String] = None,
  /* Whether the club is private. */
  `private`: Option[Boolean] = None,
  /* The club's member count. */
  member_count: Option[Int] = None,
  /* Whether the club is featured or not. */
  featured: Option[Boolean] = None,
  /* Whether the club is verified or not. */
  verified: Option[Boolean] = None,
  /* The club's vanity URL. */
  url: Option[String] = None
)

object SummaryClubEnums:
  enum SportType:
    case Cycling, Running, Triathlon, Other

    def value: String = toString.toLowerCase
