/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api

import java.time.OffsetDateTime

case class SummaryPRSegmentEffort(
  /* The unique identifier of the activity related to the PR effort. */
  pr_activity_id: Option[Long] = None,
  /* The elapsed time ot the PR effort. */
  pr_elapsed_time: Option[Int] = None,
  /* The time at which the PR effort was started. */
  pr_date: Option[OffsetDateTime] = None,
  /* Number of efforts by the authenticated athlete on this segment. */
  effort_count: Option[Int] = None
)

