/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package strava.models.api


case class Waypoint(
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  latlng: Option[Seq[Float]] = None,
  /* A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
  target_latlng: Option[Seq[Float]] = None,
  /* Categories that the waypoint belongs to */
  categories: Option[Seq[String]] = None,
  /* A title for the waypoint */
  title: Option[String] = None,
  /* A description of the waypoint (optional) */
  description: Option[String] = None,
  /* The number meters along the route that the waypoint is located */
  distance_into_route: Option[Int] = None
)

